GET http://localhost:3000/recipes/

################################

GET https://cooking-with-react.herokuapp.com/recipes

###

POST http://localhost:4200/recipes/newRecipe
Content-Type: application/json

{
	"name": "Plain Pork",
	"servings": 2,
	"cookTime": "1:00",
	"instructions": "1. Eat Pork\n 2. Eat salt",
	"ingredients": [
		{
			"name": "salt2112",
			"amount": "2 tbs"
		}
	],
	"authors": [
		{
			"name": "Daniel"
		}
	]
}

################################

DELETE http://localhost:4200/recipes/60e612c9cbfd6d31fcd0bd00
